version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    restart: unless-stopped

  mysql:
    image: mysql:8.3
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=minimal_api
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpassword
    ports:
      - "3306:3306"
    restart: unless-stopped